name: Build pull request
on:
  push:
    tags:
      - '*'

jobs:
  buildx:
    runs-on: ubuntu-preview
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: version
        run: echo ::set-output name=version::$(echo $GITHUB_REF | cut -d / -f 3)
        id: version
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
