name: Build and publish release on new tag
on:
  pull_request:
    branches: [ main ]
    types:
    - synchronize
    - opened
    - reopened

jobs:
  build_linux:
    runs-on: ubuntu-latest
    steps: 
    - name: Checkout
      uses: actions/checkout@v2
    