name: Build pull request
on:
  pull_request:
    branches: [ main ]

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Run Buildx
        run: |
          docker buildx build . \
            --progress=plain \
            --platform linux/amd64
